items=[]
n=int(input("Enter how many numbers entered in list:"))
for i in range(1,n+1):
    b=input("Enter a item:")
    items.append(b)
print(items)
c=int(input("Enter the index which is to be insert:"))
d=input("Enter a string to be inserted:")
m=items.insert(c,d)
print("After inserted element in the list:",items)
n=items.sort()
print("The sorted library items:",items)
e=input("Enter which is to be count:")
print("The number of mentioned item in library:",items.count(e))
f=int(input("Enter a index to be removed:"))
p=items.pop(f)
print("The list after removal of library:",items)
q=len(items)
print("The number of items in library:",q)
